/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_fmo_Lib */

#ifndef _Included_cz_fmo_Lib
#define _Included_cz_fmo_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_fmo_Lib
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_fmo_Lib_getHelloString
        (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    onFrame
 * Signature: (Lcz/fmo/Lib/FrameCallback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_onFrame
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
