/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_fmo_Lib */

#ifndef _Included_cz_fmo_Lib
#define _Included_cz_fmo_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_fmo_Lib
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_fmo_Lib_getHelloString
  (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    onFrame
 * Signature: (Landroid/media/Image;Lcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_onFrame
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    ocvRecStart
 * Signature: (Lcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_ocvRecStart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    ocvRecStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_ocvRecStop
  (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    ocvRec2Start
 * Signature: (IILcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_ocvRec2Start
        (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    ocvRec2Frame
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_ocvRec2Frame
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     cz_fmo_Lib
 * Method:    ocvRec2Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_ocvRec2Stop
        (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    recording2Start
 * Signature: (IILcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_recording2Start
        (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    recording2Frame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_recording2Frame
        (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cz_fmo_Lib
 * Method:    recording2Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_recording2Stop
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cz_fmo_Lib_Callback */

#ifndef _Included_cz_fmo_Lib_Callback
#define _Included_cz_fmo_Lib_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
